---
- name: "restart zabbix server"
  service:
    name: zabbix-server
    state: restarted

- name: "start and enable zabbix server on boot"
  service:
    name: zabbix-server
    state: started
    enabled: yes

- name: "restart apache"
  service:
    name: httpd
    state: restarted

