---
# ApacheとPHPセットアップ

# 設定を無効化する際にファイルを削除すると、後にアップデート時に設定が復活するので、ゼロバイトのファイルにする。
- name: welcome設定存在チェック
  stat: path=/etc/httpd/conf.d/welcome.conf
  register: welcome_stat

- name: welcome設定無効化
  command: cp /dev/null /etc/httpd/conf.d/welcome.conf
  when: welcome_stat.stat.size != 0
  notify:
      - "restart apache" 

- name: autoindex設定存在チェック
  stat: path=/etc/httpd/conf.d/autoindex.conf
  register: autoindex_stat

- name: autoindex設定無効化
  command: cp /dev/null /etc/httpd/conf.d/autoindex.conf
  when: autoindex_stat.stat.size != 0
  notify:
      - "restart apache" 

- name: userdir設定存在チェック
  stat: path=/etc/httpd/conf.d/userdir.conf
  register: userdir_stat

- name: userdir設定無効化
  command: cp /dev/null /etc/httpd/conf.d/userdir.conf
  when: userdir_stat.stat.size != 0
  notify:
      - "restart apache" 

- name: 不要なモジュールを除去した設定展開
  copy: 
    src: apache24/conf.modules.d/00-base.conf
    dest: /etc/httpd/conf.modules.d/00-base.conf
    mode: 0644
    owner: root
    group: root
  notify: "restart apache"

- name: dav設定存在チェック
  stat: path=/etc/httpd/conf.modules.d/00-dav.conf
  register: dav_stat

- name: dav設定無効化
  command: cp /dev/null /etc/httpd/conf.modules.d/00-dav.conf
  when: dav_stat.stat.size != 0
  notify:
      - "restart apache" 

- name: lua設定存在チェック
  stat: path=/etc/httpd/conf.modules.d/00-lua.conf
  register: lua_stat

- name: lua設定無効化
  command: cp /dev/null /etc/httpd/conf.modules.d/00-lua.conf
  when: lua_stat.stat.size != 0
  notify:
      - "restart apache" 

- name: ApacheのMaxClients設定を展開
  copy: 
    src: apache24/conf.modules.d/00-mpm.conf
    dest: /etc/httpd/conf.modules.d/00-mpm.conf
    mode: 0644
    owner: root
    group: root
  notify: "restart apache"

- name: 不要なモジュールを除去したProxy設定展開
  copy: 
    src: apache24/conf.modules.d/00-proxy.conf
    dest: /etc/httpd/conf.modules.d/00-proxy.conf
    mode: 0644
    owner: root
    group: root
  notify: "restart apache"

- name: cgi設定存在チェック
  stat: path=/etc/httpd/conf.modules.d/01-cgi.conf
  register: cgi_stat

- name: cgi設定無効化
  command: cp /dev/null /etc/httpd/conf.modules.d/01-cgi.conf
  when: cgi_stat.stat.size != 0
  notify:
      - "restart apache" 

- name: apache設定展開
  template: 
    src: apache24/conf/httpd.conf.j2 
    dest: /etc/httpd/conf/httpd.conf
    mode: 0644
    owner: root
    group: root
  notify: "restart apache"

- name: ssl設定展開
  copy: 
    src: apache24/conf.d/ssl.conf 
    dest: /etc/httpd/conf.d/ssl.conf
    mode: 0644
    owner: root
    group: root
  notify: "restart apache"

- name: "PHP7.2の設定展開"
  copy: 
    src: php72/php.ini 
    dest: /etc/php.ini
    mode: 0644
    owner: root
    group: root
  notify:
    - "restart apache"

- name: "PHP7.2-opcacheの設定展開"
  copy: 
    src: php72/php.d/10-opcache.ini 
    dest: /etc/php.d/10-opcache.ini
    mode: 0644
    owner: root
    group: root
  notify:
    - "restart apache" 

- name: ログディレクトリパーミッション設定
  file:
    path: /var/log/httpd
    mode: 0755

# コケるとnotifyがうまく動かないので念のため。
- name: "start and enable apache on boot"
  service: name=httpd state=started enabled=yes

